### ISSUE TITLE
Manage TCP port for X Protocol

### ISSUE THREAD

**Issue by dveeden** [datacharmer/mysql-sandbox#22]
MySQL Sandbox does change the mysql port (3306) for the client and server to make it possible to use multiple sandboxes on the same host. However it does not change the port for the mysqlx port (33060).

Suggestion: Set the mysqlx port to 10 x classic_port (e.g. add a zero to the portnumber) or use the next free port after 33060 (first sandbox 33061, second 33062, etc).

**Comment by datacharmer** [comment]
This is only doable if the plugin is installed using plugin_load during initialization, because mysqlx_port is not dynamic.
The implementation for this feature requires a new option that will install the plugin and set the port at once.

A workaround to do it currently is

make_sandbox 5.7.14 -- -c plugin_load=mysqlx:mysqlx.so -c mysqlx_port=15714

**Comment by datacharmer** [comment]
The new option, with an updated mysqlsh script, will be published in a few days.

**Comment by datacharmer** [comment]
There are now (MySQL-Sandbox 3.2.00) two new arguments:
--plugin_mysqlx   (installs the plugin at startup)
and, optionally: --mysqlx_port=i (sets the wanted port. By default is sandbox port + 10,000)
