### ISSUE TITLE
mysqlsh script broken in MySQL Shell 8.0.0 dmr

### ISSUE THREAD

**Issue by morgo** [datacharmer/mysql-sandbox#38]
```
morgo@ryzen:~/sandboxes/msb_5_7_18$ ./mysqlsh 
Conflicting options: port and socket can not be used together.

```
I worked around this by removing the socket option.  Not sure what you would like to do as a proper fix:
```
            --port=8003 "$@"
#            --socket=/tmp/mysql_sandbox8003.sock "$@"
```

**Comment by datacharmer** [comment]
This issue is due to fact that mysqlsh is not distributed with the server. You are probably using a version of mysqlsh later than 1.0.9, which has a check for the conflicting option.
The proper fix would be for the script to point to the version of mysqlsh that is appropriate for the current server version. Using a globally installed mysqlsh will always lead to this kind of errors.
It does not help that mysqlsh can't read options from a file.

**Comment by morgo** [comment]
I am using the version mentioned in the title (8.0.0 dmr) - available for download under"development releases".

This is an improvement over the previous version, as it is ambiguous which setting to make use of when they conflict.

**Comment by datacharmer** [comment]
I could remove the socket option, although I really dislike this kind of shot-in-the-dark development. The main principle of MySQL Sandbox is that it uses the tools that are appropriate for each version. With the global-only mysqlsh, there is no guarantee that the options coded in the script will be right.

I will change the script during the week-end.

**Comment by datacharmer** [comment]
Changed in version 3.2.11
