### ISSUE TITLE
Global alias for alternative editor

### ISSUE THREAD

**Issue by morgo** [datacharmer/mysql-sandbox#39]
A feature request for your consideration:

I really like the `msb` global alias to be able to load a shell for something like `msb 803`.  I've found myself adding the alias `msbsh` so that I can explicitly launch a session with an alternative editor (the ./use command is hard-coded in msb).

I'm not sure if it's better to have an environment variable here - or aliases.  As a developer, I find myself wanting to sometimes try things in both shells.

**Comment by datacharmer** [comment]
This is a bit more complicated than it looks. I can get the script to execute ./mysqlsh (or the global mysqlsh) instead of ./use but the two tools are not compatible, even more so because the .mysqlsh script is a hack that was supposed to be temporary, waiting for the mysql shell to be distributed with the server: this is taking longer than expected.
The  ./use command is already able to use a $MYSQL_EDITOR instead of  $BASEDIR/mysql, but the tool is invoked with --defaults-file=my.sandbox.cnf, which is not understood by mysqlsh.

**Comment by datacharmer** [comment]
If you have a solution in mind, either as a patch or as an additional tool, I would appreciate a contribution.
